# coding: utf-8

"""
    Kill Bill

    Kill Bill is an open-source billing and payments platform  # noqa: E501

    OpenAPI spec version: 1.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import killbill
from killbill.models.unit_usage_record import UnitUsageRecord  # noqa: E501
from killbill.rest import ApiException


class TestUnitUsageRecord(unittest.TestCase):
    """UnitUsageRecord unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testUnitUsageRecord(self):
        """Test UnitUsageRecord"""
        # FIXME: construct object with mandatory attributes with example values
        # model = killbill.models.unit_usage_record.UnitUsageRecord()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
