# coding: utf-8

#
# Copyright 2014-2017 Groupon, Inc.
# Copyright 2014-2017 The Billing Project, LLC
#
# The Billing Project, LLC licenses this file to you under the Apache License, version 2.0
# (the "License"); you may not use this file except in compliance with the
# License.  You may obtain a copy of the License at:
#
#    http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS, WITHOUT
# WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.  See the
# License for the specific language governing permissions and limitations
# under the License.
#

"""
    Kill Bill

    Kill Bill is an open-source billing and payments platform  # noqa: E501

    OpenAPI spec version: 1.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import killbill
from killbill.models.payment_method_plugin_detail import PaymentMethodPluginDetail  # noqa: E501
from killbill.rest import ApiException


class TestPaymentMethodPluginDetail(unittest.TestCase):
    """PaymentMethodPluginDetail unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testPaymentMethodPluginDetail(self):
        """Test PaymentMethodPluginDetail"""
        # FIXME: construct object with mandatory attributes with example values
        # model = killbill.models.payment_method_plugin_detail.PaymentMethodPluginDetail()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
