# coding: utf-8

#
# Copyright 2014-2017 Groupon, Inc.
# Copyright 2014-2017 The Billing Project, LLC
#
# The Billing Project, LLC licenses this file to you under the Apache License, version 2.0
# (the "License"); you may not use this file except in compliance with the
# License.  You may obtain a copy of the License at:
#
#    http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS, WITHOUT
# WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.  See the
# License for the specific language governing permissions and limitations
# under the License.
#

"""
    Kill Bill

    Kill Bill is an open-source billing and payments platform  # noqa: E501

    OpenAPI spec version: 1.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import killbill
from api.overdue_api import OverdueApi  # noqa: E501
from killbill.rest import ApiException


class TestOverdueApi(unittest.TestCase):
    """OverdueApi unit test stubs"""

    def setUp(self):
        self.api = api.overdue_api.OverdueApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_get_overdue_config_json(self):
        """Test case for get_overdue_config_json

        Retrieve the overdue config as JSON  # noqa: E501
        """
        pass

    def test_get_overdue_config_xml(self):
        """Test case for get_overdue_config_xml

        Retrieve the overdue config as XML  # noqa: E501
        """
        pass

    def test_upload_overdue_config_json(self):
        """Test case for upload_overdue_config_json

        Upload the full overdue config as JSON  # noqa: E501
        """
        pass

    def test_upload_overdue_config_xml(self):
        """Test case for upload_overdue_config_xml

        Upload the full overdue config as XML  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
