# coding: utf-8

#
# Copyright 2014-2017 Groupon, Inc.
# Copyright 2014-2017 The Billing Project, LLC
#
# The Billing Project, LLC licenses this file to you under the Apache License, version 2.0
# (the "License"); you may not use this file except in compliance with the
# License.  You may obtain a copy of the License at:
#
#    http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS, WITHOUT
# WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.  See the
# License for the specific language governing permissions and limitations
# under the License.
#

"""
    Kill Bill

    Kill Bill is an open-source billing and payments platform  # noqa: E501

    OpenAPI spec version: 1.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import killbill
from api.subscription_api import SubscriptionApi  # noqa: E501
from killbill.rest import ApiException


class TestSubscriptionApi(unittest.TestCase):
    """SubscriptionApi unit test stubs"""

    def setUp(self):
        self.api = api.subscription_api.SubscriptionApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_add_subscription_blocking_state(self):
        """Test case for add_subscription_blocking_state

        Block a subscription  # noqa: E501
        """
        pass

    def test_cancel_subscription_plan(self):
        """Test case for cancel_subscription_plan

        Cancel an entitlement plan  # noqa: E501
        """
        pass

    def test_change_subscription_plan(self):
        """Test case for change_subscription_plan

        Change entitlement plan  # noqa: E501
        """
        pass

    def test_create_subscription(self):
        """Test case for create_subscription

        Create an subscription  # noqa: E501
        """
        pass

    def test_create_subscription_custom_fields(self):
        """Test case for create_subscription_custom_fields

        Add custom fields to subscription  # noqa: E501
        """
        pass

    def test_create_subscription_tags(self):
        """Test case for create_subscription_tags

        Add tags to subscription  # noqa: E501
        """
        pass

    def test_create_subscription_with_add_ons(self):
        """Test case for create_subscription_with_add_ons

        Create an entitlement with addOn products  # noqa: E501
        """
        pass

    def test_create_subscriptions_with_add_ons(self):
        """Test case for create_subscriptions_with_add_ons

        Create multiple entitlements with addOn products  # noqa: E501
        """
        pass

    def test_delete_subscription_custom_fields(self):
        """Test case for delete_subscription_custom_fields

        Remove custom fields from subscription  # noqa: E501
        """
        pass

    def test_delete_subscription_tags(self):
        """Test case for delete_subscription_tags

        Remove tags from subscription  # noqa: E501
        """
        pass

    def test_get_subscription(self):
        """Test case for get_subscription

        Retrieve a subscription by id  # noqa: E501
        """
        pass

    def test_get_subscription_custom_fields(self):
        """Test case for get_subscription_custom_fields

        Retrieve subscription custom fields  # noqa: E501
        """
        pass

    def test_get_subscription_tags(self):
        """Test case for get_subscription_tags

        Retrieve subscription tags  # noqa: E501
        """
        pass

    def test_modify_subscription_custom_fields(self):
        """Test case for modify_subscription_custom_fields

        Modify custom fields to subscription  # noqa: E501
        """
        pass

    def test_uncancel_subscription_plan(self):
        """Test case for uncancel_subscription_plan

        Un-cancel an entitlement  # noqa: E501
        """
        pass

    def test_undo_change_subscription_plan(self):
        """Test case for undo_change_subscription_plan

        Undo a pending change plan on an entitlement  # noqa: E501
        """
        pass

    def test_update_subscription_bcd(self):
        """Test case for update_subscription_bcd

        Update the BCD associated to a subscription  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
