# coding: utf-8

"""
    Kill Bill

    Kill Bill is an open-source billing and payments platform  # noqa: E501

    OpenAPI spec version: 1.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import killbill
from killbill.models.account_timeline import AccountTimeline  # noqa: E501
from killbill.rest import ApiException


class TestAccountTimeline(unittest.TestCase):
    """AccountTimeline unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testAccountTimeline(self):
        """Test AccountTimeline"""
        # FIXME: construct object with mandatory attributes with example values
        # model = killbill.models.account_timeline.AccountTimeline()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
